"""empty message

Revision ID: 929b578e51af
Revises: 49178f286b0c
Create Date: 2026-01-19 02:22:53.295081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929b578e51af'
down_revision = '49178f286b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.alter_column('session_token',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.alter_column('session_token',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
